project:
  type: website
  output-dir: docs

website:
  title: "Bruce Zhang"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



